pragma user_version=221;
CREATE TABLE backup_metadata (created_timestamp INT, schema_version INT, backup_id TEXT);
CREATE TABLE conversation_participants_backup (_id INTEGER PRIMARY KEY, conversation_id INT REFERENCES conversations_backup(_id) ON DELETE CASCADE , participant_id INT REFERENCES participants_backup(_id) ON DELETE CASCADE , is_normalized INT, rcs_group_join_status INT, is_c2p_only INT, UNIQUE(conversation_id,participant_id) ON CONFLICT FAIL);
CREATE INDEX index_conversation_participants_backup_conversation_id ON conversation_participants_backup(conversation_id);
CREATE INDEX index_conversation_participants_backup_participant_id ON conversation_participants_backup(participant_id);
CREATE INDEX index_conversation_participants_backup_is_c2p_only ON conversation_participants_backup(is_c2p_only);
CREATE TABLE conversation_pins_backup (_id INTEGER PRIMARY KEY, conversation_id INTEGER REFERENCES conversations_backup(_id) ON DELETE CASCADE , pin_status INTEGER);
CREATE INDEX index_conversation_pins_backup_conversation_id ON conversation_pins_backup(conversation_id);
CREATE TABLE conversations_backup (_id INTEGER PRIMARY KEY, current_my_identity TEXT REFERENCES my_identities_backup(token) ON DELETE NO ACTION ON UPDATE CASCADE, snippet_text TEXT, archive_status INT DEFAULT(0), most_recent_timestamp_ms INT, subject TEXT, name TEXT, name_is_automatic INTEGER DEFAULT(1), has_rbm_participant INT, rcs_group_self_msisdn TEXT, rcs_group_id TEXT, rcs_conference_uri TEXT, rcs_group_capabilities INT, error_state INT, rcs_subject_change_timestamp_ms INTEGER, join_state INT, conversation_type INT, send_mode INT DEFAULT(0), cms_id TEXT, cms_life_cycle INT);
CREATE INDEX index_conversations_backup_rcs_group_id ON conversations_backup(rcs_group_id);
CREATE INDEX index_conversations_backup_cms_id ON conversations_backup(cms_id);
CREATE INDEX index_conversations_backup_current_my_identity ON conversations_backup(current_my_identity);
CREATE TABLE extension_banner_conversations_backup (banner_id TEXT PRIMARY KEY NOT NULL, extensions_table_id TEXT NOT NULL REFERENCES extensions_backup(extension_id) ON DELETE CASCADE , conversation_id INTEGER NOT NULL REFERENCES conversations_backup(_id) ON DELETE CASCADE , banner_text TEXT NOT NULL);
CREATE INDEX index_extension_banner_conversations_backup_extensions_table_id ON extension_banner_conversations_backup(extensions_table_id);
CREATE INDEX index_extension_banner_conversations_backup_conversation_id ON extension_banner_conversations_backup(conversation_id);
CREATE TABLE extension_banner_messages_backup (banner_id TEXT NOT NULL REFERENCES extension_banner_conversations_backup(banner_id) ON DELETE CASCADE , message_id INTEGER NOT NULL REFERENCES messages_backup(_id) ON DELETE CASCADE , message_uuid TEXT NOT NULL, PRIMARY KEY (banner_id,message_id));
CREATE INDEX index_extension_banner_messages_backup_banner_id ON extension_banner_messages_backup(banner_id);
CREATE INDEX index_extension_banner_messages_backup_message_id ON extension_banner_messages_backup(message_id);
CREATE INDEX index_extension_banner_messages_backup_message_uuid ON extension_banner_messages_backup(message_uuid);
CREATE TABLE extension_conversations_backup (conversation_uuid TEXT PRIMARY KEY NOT NULL, conversation_id INTEGER NOT NULL REFERENCES conversations_backup(_id) ON DELETE CASCADE , extensions_table_id TEXT NOT NULL REFERENCES extensions_backup(extension_id) ON DELETE CASCADE );
CREATE INDEX index_extension_conversations_backup_conversation_id ON extension_conversations_backup(conversation_id);
CREATE INDEX index_extension_conversations_backup_extensions_table_id ON extension_conversations_backup(extensions_table_id);
CREATE TABLE extension_messages_backup (_id TEXT PRIMARY KEY NOT NULL, message_id INTEGER NOT NULL REFERENCES messages_backup(_id) ON DELETE CASCADE , is_latest INT, session_uuid TEXT NOT NULL, message_uuid TEXT NOT NULL, extensions_table_id TEXT NOT NULL REFERENCES extensions_backup(extension_id) ON DELETE CASCADE , sender_recipient_uuid TEXT NOT NULL, extension_message_type INTEGER DEFAULT(0), data_uri TEXT, summary_text TEXT, original_media_uri TEXT, media_uri TEXT, media_content_type TEXT, image_title TEXT, image_subtitle TEXT, caption TEXT, subcaption TEXT, trailing_caption TEXT, trailing_subcaption TEXT, created_timestamp INTEGER, interaction_mode INTEGER DEFAULT(0));
CREATE INDEX index_extension_messages_backup_message_id ON extension_messages_backup(message_id);
CREATE INDEX index_extension_messages_backup_is_latest ON extension_messages_backup(is_latest);
CREATE INDEX index_extension_messages_backup_session_uuid ON extension_messages_backup(session_uuid);
CREATE INDEX index_extension_messages_backup_message_uuid ON extension_messages_backup(message_uuid);
CREATE INDEX index_extension_messages_backup_extensions_table_id ON extension_messages_backup(extensions_table_id);
CREATE TABLE extension_recipients_backup (recipient_uuid TEXT PRIMARY KEY NOT NULL, conversation_id INTEGER NOT NULL REFERENCES conversations_backup(_id) ON DELETE CASCADE , extensions_table_id TEXT NOT NULL REFERENCES extensions_backup(extension_id) ON DELETE CASCADE , my_identity_token TEXT REFERENCES my_identities_backup(token) ON DELETE CASCADE ON UPDATE CASCADE, participant_id INTEGER REFERENCES participants_backup(_id) ON DELETE CASCADE );
CREATE INDEX index_extension_recipients_backup_conversation_id ON extension_recipients_backup(conversation_id);
CREATE INDEX index_extension_recipients_backup_extensions_table_id ON extension_recipients_backup(extensions_table_id);
CREATE INDEX index_extension_recipients_backup_my_identity_token ON extension_recipients_backup(my_identity_token);
CREATE INDEX index_extension_recipients_backup_participant_id ON extension_recipients_backup(participant_id);
CREATE TABLE link_preview_backup (_id INTEGER PRIMARY KEY AUTOINCREMENT, message_id INTEGER NOT NULL UNIQUE ON CONFLICT FAIL REFERENCES messages_backup(_id) ON DELETE CASCADE , trigger_url TEXT NOT NULL, expiration_time_millis INTEGER DEFAULT(0), link_title TEXT, link_description TEXT, link_image_url TEXT, link_domain TEXT, link_canonical_url TEXT);
CREATE TABLE message_captions_backup (message_id INTEGER REFERENCES messages_backup(_id) ON DELETE CASCADE , caption TEXT);
CREATE UNIQUE INDEX index_message_captions_backup_message_id ON message_captions_backup(message_id);
CREATE TABLE message_reactions_backup (_id INTEGER PRIMARY KEY AUTOINCREMENT, message_id INTEGER NOT NULL REFERENCES messages_backup(_id) ON DELETE CASCADE , reactions_data BLOB, reacted_message_id INTEGER REFERENCES messages_backup(_id) ON DELETE CASCADE , reaction INTEGER, applied_reaction BLOB);
CREATE INDEX index_message_reactions_backup_message_id ON message_reactions_backup(message_id);
CREATE INDEX index_message_reactions_backup_reacted_message_id ON message_reactions_backup(reacted_message_id);
CREATE TABLE message_replies_backup (message_id INTEGER PRIMARY KEY REFERENCES messages_backup(_id) ON DELETE CASCADE , replied_to_message_id INTEGER REFERENCES messages_backup(_id) ON DELETE CASCADE , replied_to_message_id_null_reason INTEGER, replied_to_rcs_message_id TEXT);
CREATE INDEX index_message_replies_backup_replied_to_message_id ON message_replies_backup(replied_to_message_id);
CREATE INDEX index_message_replies_backup_replied_to_message_id_null_reason ON message_replies_backup(replied_to_message_id_null_reason);
CREATE INDEX index_message_replies_backup_replied_to_rcs_message_id ON message_replies_backup(replied_to_rcs_message_id);
CREATE TABLE message_star_backup (_id INTEGER PRIMARY KEY, message_id INTEGER REFERENCES messages_backup(_id) ON DELETE CASCADE );
CREATE INDEX index_message_star_backup_message_id ON message_star_backup(message_id);
CREATE TABLE messages_backup (_id INTEGER PRIMARY KEY, message_persistence_id TEXT, my_identity TEXT REFERENCES my_identities_backup(token) ON DELETE NO ACTION ON UPDATE CASCADE, message_status INT, seen INT, read INT, conversation_id INT REFERENCES conversations_backup(_id) ON DELETE CASCADE , sender_participant_id INT REFERENCES participants_backup(_id) ON DELETE CASCADE , sender_send_destination TEXT, msisdn_receiving_rcs_message TEXT, self_participant_id INT REFERENCES participants_backup(_id) ON DELETE CASCADE , mms_subject TEXT, received_timestamp INT, sent_timestamp INT, protocol INT, message_priority INT, rcs_encryption_status INT, cloud_sync_id TEXT, correlation_id TEXT, sms_error_code INT DEFAULT(-1), sms_error_desc_map_name TEXT, mms_transaction_id TEXT, mms_content_location TEXT, is_hidden INT, rcs_message_id TEXT, custom_headers BLOB, cms_id TEXT, cms_life_cycle INT, cms_correlation_id TEXT, cms_last_mod_seq INTEGER, created_by_feature INT DEFAULT(0));
CREATE INDEX index_messages_backup_conversation_id ON messages_backup(conversation_id);
CREATE INDEX index_messages_backup_sender_participant_id ON messages_backup(sender_participant_id);
CREATE INDEX index_messages_backup_self_participant_id ON messages_backup(self_participant_id);
CREATE INDEX index_messages_backup_received_timestamp ON messages_backup(received_timestamp);
CREATE INDEX index_messages_backup_rcs_message_id ON messages_backup(rcs_message_id);
CREATE INDEX index_messages_backup_cms_id ON messages_backup(cms_id);
CREATE INDEX index_messages_backup_cms_correlation_id ON messages_backup(cms_correlation_id);
CREATE INDEX index_messages_backup_custom_headers ON messages_backup(custom_headers);
CREATE INDEX index_messages_backup_my_identity ON messages_backup(my_identity);
CREATE UNIQUE INDEX index_messages_backup_message_persistence_id ON messages_backup(message_persistence_id) WHERE message_persistence_id NOT NULL;
CREATE TABLE my_identities_backup (token TEXT PRIMARY KEY NOT NULL, canonical_token TEXT REFERENCES my_identities_backup(token) ON DELETE NO ACTION ON UPDATE CASCADE, address_type INT, phone_number TEXT, provisioning_id TEXT, is_verified INT, display_name TEXT);
CREATE INDEX index_my_identities_backup_canonical_token ON my_identities_backup(canonical_token);
CREATE TABLE participants_backup (_id INTEGER PRIMARY KEY, my_identity_token_foreign_key TEXT REFERENCES my_identities_backup(token) ON DELETE NO ACTION ON UPDATE CASCADE, normalized_destination TEXT, send_destination TEXT, display_destination TEXT, first_name TEXT, full_name TEXT, is_self INT, blocked INT, participant_type INT, is_spam INT, is_spam_source INT, country_code TEXT, color_palette_index INT DEFAULT(-1), color_type INT DEFAULT(0), extended_color INT DEFAULT(0), cms_id TEXT, cms_life_cycle INT);
CREATE INDEX index_participants_backup_normalized_destination ON participants_backup(normalized_destination);
CREATE INDEX index_participants_backup_cms_id ON participants_backup(cms_id);
CREATE INDEX index_participants_backup_my_identity_token_foreign_key ON participants_backup(my_identity_token_foreign_key);
CREATE TABLE parts_backup (_id INTEGER PRIMARY KEY, message_id INT REFERENCES messages_backup(_id) ON DELETE CASCADE , content_type TEXT, source INT DEFAULT(13), text TEXT, width INT DEFAULT(-1), height INT DEFAULT(-1), longitude REAL, latitude REAL, cms_full_size_blob_id TEXT, cms_media_encryption_key BLOB, cms_compressed_media_encryption_key BLOB, cms_compressed_blob_id TEXT, file_name TEXT, duration INT);
CREATE INDEX index_parts_backup_message_id ON parts_backup(message_id);
CREATE TABLE read_reports_backup (_id INTEGER PRIMARY KEY AUTOINCREMENT, message_id INT NOT NULL REFERENCES messages_backup(_id) ON DELETE CASCADE , participant_id INT NOT NULL REFERENCES participants_backup(_id) ON DELETE CASCADE , receive_time INT DEFAULT(0), read_time INT DEFAULT(0), ftd_time INTEGER DEFAULT(-1));
CREATE INDEX index_read_reports_backup_message_id ON read_reports_backup(message_id);
CREATE INDEX index_read_reports_backup_participant_id ON read_reports_backup(participant_id);
CREATE TABLE settings_backup (_id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT NOT NULL, sub_key TEXT, data BLOB);
CREATE UNIQUE INDEX index_settings_keys ON settings_backup(key, sub_key);
CREATE TABLE user_reference_backup (_id INTEGER PRIMARY KEY, message_id INTEGER REFERENCES messages_backup(_id) ON DELETE CASCADE , user_ref_id INTEGER NOT NULL REFERENCES participants_backup(_id) ON DELETE CASCADE , user_ref_datetime INTEGER, UNIQUE(message_id,user_ref_id) ON CONFLICT IGNORE);
